### ISSUE TITLE
are there more soejrd delights?

### ISSUE THREAD

**Issue by KeLaiFu** [soejrd/KOCMOC-SVF#1]
I recall seeing a post, probably on MW of a whole line up of mutables and other open source modules rendered in your clean style. Are any of those reality? I'm looking for a version of grids and I am sure you had one that looked awesome.

**Comment by soejrd** [comment]
Most of them are a reality yes. I will open source those panel designs in the future, no date yet. As far as the MI panel redesigns go, most are just a panel swap, so the underlying layout/pcb is the same.
